pages:
 # key is the dirname of pages in src/pages
 home:
  # 首页配置
  zh-cn:
   title: 'suveng'
   keywords: 'suveng,blog'
   description: 'this is suveng blog'
  # home config
  en-us:
   title: 'suveng'
   keywords: 'suveng,blog'
   description: 'this is suveng blog'
 community:
  # 社区页配置
  zh-cn:
   title: 'suveng'
   keywords: 'suveng,blog'
   description: 'this is suveng blog'
  # community page config
  en-us:
   title: 'suveng'
   keywords: 'suveng,blog'
   description: 'this is suveng blog'
 blog:
  # 博客列表页配置
  zh-cn:
   title: 'suveng'
   keywords: 'suveng,blog'
   description: 'this is suveng blog'
  en-us:
   # blog list page config
   title: 'suveng'
   keywords: 'suveng,blog'
   description: 'this is suveng blog'